// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYWYR3Bpcj82a71lxfhjoVAtAuuKqxOYA',
    appId: '1:871663645719:web:7958fd1f5ace38ddd65852',
    messagingSenderId: '871663645719',
    projectId: 'thesecretofcoffe',
    authDomain: 'thesecretofcoffe.firebaseapp.com',
    storageBucket: 'thesecretofcoffe.appspot.com',
    measurementId: 'G-VXRV932V85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf7ubrb7kJxjiMT3Tg4KLWTM7oIidINgk',
    appId: '1:871663645719:android:30df2b752605648ed65852',
    messagingSenderId: '871663645719',
    projectId: 'thesecretofcoffe',
    storageBucket: 'thesecretofcoffe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtS3Etu6LcZQu8xYeYyPOCcZ9pLSDXk20',
    appId: '1:871663645719:ios:ac0e4d1cf213fb43d65852',
    messagingSenderId: '871663645719',
    projectId: 'thesecretofcoffe',
    storageBucket: 'thesecretofcoffe.appspot.com',
    iosClientId: '871663645719-qufbcu0ng2jrh6srb2gh68duf4eavog9.apps.googleusercontent.com',
    iosBundleId: 'com.example.theSecretOfCoffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtS3Etu6LcZQu8xYeYyPOCcZ9pLSDXk20',
    appId: '1:871663645719:ios:ac0e4d1cf213fb43d65852',
    messagingSenderId: '871663645719',
    projectId: 'thesecretofcoffe',
    storageBucket: 'thesecretofcoffe.appspot.com',
    iosClientId: '871663645719-qufbcu0ng2jrh6srb2gh68duf4eavog9.apps.googleusercontent.com',
    iosBundleId: 'com.example.theSecretOfCoffee',
  );
}
